title = "Hugo blog theme"
baseURL = 'https://example.com'

defaultContentLanguage = "ja-jp"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
theme = "hugo-take-theme"

[params]
DateForm = "2006.1.2"

[markup]
[markup.highlight]
noClasses = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[Languages.ja-jp]
languageName = "Japanese"
languageCode = "ja-jp"
contentDir = "content/"

[Languages.ja-jp.params]
mainSections = ['posts']
dateFormat = "2 May 2023"

[outputFormats]
[outputFormats.llms]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true
rel = "alternate"
root = true

[outputFormats.llmsfull]
mediaType = "text/plain"
baseName = "llms-full"
isPlainText = true
rel = "alternate"
root = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "Sitemap", "RSS", "llms", "llmsfull"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML", "RSS"]
page = ["HTML"]
